"""add_brands_social_accounts_and_brand_id_fk

Revision ID: 1bb82e951204
Revises: 26d0374648c7
Create Date: 2026-07-14 12:07:17.443731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '1bb82e951204'
down_revision: Union[str, None] = '26d0374648c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='brandstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('social_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('instagram', 'facebook', 'whatsapp', name='socialplatform'), nullable=False),
    sa.Column('platform_account_id', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brand_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tasks', sa.Column('brand_id', sa.Integer(), nullable=True))
    op.alter_column('tasks', 'brand_name',
               existing_type=sa.String(length=200),
               nullable=True)
    op.create_foreign_key(None, 'tasks', 'brands', ['brand_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.alter_column('tasks', 'brand_name',
               existing_type=sa.String(length=200),
               nullable=False)
    op.drop_column('tasks', 'brand_id')
    op.drop_table('brand_assignments')
    op.drop_table('social_accounts')
    op.drop_table('brands')
    # ### end Alembic commands ###
